#!/bin/bash -e

SCRIPTDIR=$(dirname $0)/toolchainscripts

source $SCRIPTDIR/functions

for script in $(ls $SCRIPTDIR | grep ^[0-9]); do
	if [ "$1" = "fetch" ]; then
		SRC=$LFS/var/cache/scratchpkg/sources $SCRIPTDIR/$script "$1"
	elif [ -f /tools/"$script" ]; then
		echo "--- $script skipped ---"
	else
		echo "*** $script ***"
		SRC=$LFS/var/cache/scratchpkg/sources $SCRIPTDIR/$script
		echo; echo "*** $script done ***"; echo
		[ "$1" = $(echo $script | cut -d - -f1) ] && exit
	fi
done

[ "$1" = "fetch" ] && exit 0

sudo chown -Rv 0:0 $LFS

echo
echo "**************************************************"
echo "*********    Toolchain build complete    *********"
echo "**************************************************"
