#!/bin/bash -e

source $(dirname $0)/functions
source $(dirname $0)/pkgversion

filename=$(echo $0 | rev | cut -d / -f1 | rev)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=curl
VERSION=${CURL_VER}

fetch "https://curl.haxx.se/download/$NAME-$VERSION.tar.xz" $SRC

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

tar xf $SRC/$tarballname -C $TMP

{ time \
   {

	cd $TMP/$NAME-$VERSION

	 ./configure \
			--prefix=/tools            \
			--with-ssl                 \
			--enable-threaded-resolver \
			--with-ca-bundle=/tools/etc/ssl/certs/ca-certificates.crt
	make
	make install
	
	}
} 2>&1 | tee $LOG/$filename.log
    
[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
